### ISSUE TITLE
UnityAndroid plugin doesn't work with new hockeyapp crashmanager

### ISSUE THREAD

**Issue by liszto** [bitstadium/HockeySDK-Unity-Android#24]
Hello !
We use your SDK for a while now but in the last version (5.0.2) we probably found an issue quite annoying. The plugin doesn't work at all :(

The issue comes from this line in your unity script : 
`crashReporterKey =  jc.CallStatic<string>("getCrashReporterKey");`

Cause there is no "getCrashReporterKey" method in the Android script version now. Is it normal you keep the method call in your cs script ? (cause for me it's not ;) )
By doing this we can see no logs created in our log path at /Logs/MyLogs-date.log

We tried to confirm this to remove the : 
`crashReporterKey =  jc.CallStatic<string>("getCrashReporterKey");`
from your cs script and after this, the log is created in a good way cause we can see them in our android application space.

But when we restart the app to autosend them, they seem to be send but not display in our app backlog on your website, probably due to a formatting issue cause your system seems to be different now.

Could you please fix asap cause it's really a huge issue for us :/ or at least give us a workaround.

thanks in advance,

MOREL Aurelien.

**Comment by bmourat** [comment]
Hey, @liszto!

Thanks for reporting this issue. I've looked into it and indeed there was a bug with getCrashReporterKey method being missing. It will be fixed in next release. As for the crashes not appearing in the HockeyApp, sometimes there can be some delay between uploading logs and them being processed. I've tried it, and after removing getCrashReporterKey call all logs appeared on the portal. If your crash doesn't appear, could you please provide some sample code to reproduce this crash, so we could investigate why it is not being shown on the portal. Thanks again!

Best,
Murat.

**Comment by liszto** [comment]
Hello ! 
Thanks for this fix (we did the same this morning).
We gonna investigate a little bit more from our side cause it seems the Unity log file aren't send to the server cause we still find them in android/data/bundle_id/files/logs even after restart the app :/

BUT

the pure Android crash seems to be send cause in our app we received a crash due to a native plugin. But all our crash due to Unity exception aren't send

If you have a hint concerning this, feel free to share, we gonna check this tomorrow morning if you need more information.

**Comment by liszto** [comment]
Any idea on our last comment ?

**Comment by bmourat** [comment]
Hey, unfortunately, I don't have any ideas as for why logs are not transferred. But maybe we can debug this. I've added extra debug outputs to the script and if you could run your app with this script and provide logcat output, I think we could figure out what the problem is. Here is the script: https://gist.github.com/bmourat/cef0153b3ed23fb8e6e7371df502b5f6

Best,
Murat

**Comment by liszto** [comment]
Thanks we gonna test this asap. So probably this afternoon !

**Comment by liszto** [comment]
nevermind ! We get WiFi hotspot but in fact we didn't connect our device through the portal :( 
So the logs are uploaded after the 
`crashReporterKey = jc.CallStatic<string>("getCrashReporterKey");`
fix !

So far so good as we said !

Thanks again for your debugging script :) and in your debugging script there is maybe another issue with this java call : 
`pluginClass.CallStatic("performAuthentication", currentActivity);`
performAuthentication seems to be missing in your unity android wrapper ;)

MOREL A.

**Comment by bmourat** [comment]
Glad you've figured your issue out! performAuthentication method is for future release, so don't pay attention to it. I don't think you will have a problem with crashreporterkey on iOS, the method is still there.

Murat

**Comment by liszto** [comment]
Thanks a lot !
